# Generated by Django 4.0.4 on 2022-07-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_readers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readers',
            name='favorites',
        ),
        migrations.AddField(
            model_name='readers',
            name='favorites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='blog.post'),
            preserve_default=False,
        ),
    ]
