# Generated by Django 4.0.4 on 2022-07-09 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_remove_post_favorites_readers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readers',
            name='user',
        ),
        migrations.AlterField(
            model_name='readers',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
